### ISSUE TITLE
com.jdroid.github.client.RequestException: Bad credentials (401)

### ISSUE THREAD

**Issue by savvisingh** [dipien/releases-hub-gradle-plugin#107]
**Describe the bug**
upgradDependencies always fails with "com.jdroid.github.client.RequestException: Bad credentials (401)"
I have tried using secrets.GITHUB_TOKEN from Github Actions Workflow and even tried hardcoding the personal token with all the permissions But it always result in the same error.
The weird thing is I can see that the plugin is creating branches But not able to create Pull requests.

I am stuck on this error for days, Would be really helpful if someone can tell me what I am doing wrong :(
**To Reproduce**
```
name: UpgradeDependencies
 -uses: actions/checkout@v2     
 - name: UpgradeDependencies        
 - run:  ./gradlew upgradeDependencies -PgitHubWriteToken=${{ secrets.GITHUB_TOKEN }} -PgitHubUserEmail=sabbispeak@gmail.com -PgitHubUserName=savvisingh
````

And My Gradle file has this configuration
```
plugins{
    id("com.dipien.releaseshub.gradle.plugin") version "2.0.2"
}

releasesHub {
    dependenciesClassNames = listOf("Dependencies.kt")
    dependenciesBasePath = "buildSrc/src/main/java/"
    gitHubRepositoryOwner = "savvisingh"
    gitHubRepositoryName = "coil-sample"
}
```

**Comment by maxirosson** [comment]
There is a problem with your Github write token, used by the plugin to create a pull request. Please verify if you are properly sending the token and if it has write permissions.

**Comment by savvisingh** [comment]
If you mean Personal Access Token I have given all the permissions fo the token But Still it shows the same error :(

**Comment by maxirosson** [comment]
Did you follow these steps when creating the token? https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

It's important you have checked the `repo` permissions
