### ISSUE TITLE
Gradle version catalogs support

### ISSUE THREAD

**Issue by maxirosson** [dipien/releases-hub-gradle-plugin#113]
https://docs.gradle.org/current/userguide/platforms.html

As part of this issue, the basic notation is supported on the libs.versions.toml file:

[libraries]
groovy-core = "org.codehaus.groovy:groovy:3.0.5"
groovy-json = "org.codehaus.groovy:groovy-json:3.0.5"
groovy-nio = "org.codehaus.groovy:groovy-nio:3.0.5"

The support for `[versions]` tag will be implemented as part of this issue: https://github.com/dipien/releases-hub-gradle-plugin/issues/17

**Comment by nachtien** [comment]
Yes!  Nice work!  At the moment DependencyBot doesn't support it, making this plugin the only one capable of creating PR's for dependency updates :).  When do you think you'll release 3.0?

**Comment by nachtien** [comment]
ah gotcha.  Thanks for the message back.  

If I just delete the `version.ref` from each of my module, so: 
`ktor-clientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }`
becomes 
`ktor-clientAndroid = { module = "io.ktor:ktor-client-android"}`
Would this plugin be smart enough to upgrade it?

**Comment by maxirosson** [comment]
The basic notation is supported on the libs.versions.toml file:

For example:
```
[libraries]
groovy-core = "org.codehaus.groovy:groovy:3.0.5"
groovy-json = "org.codehaus.groovy:groovy-json:3.0.5"
groovy-nio = "org.codehaus.groovy:groovy-nio:3.0.5"
```
